spring:
  redis:
    host: 192.168.193.129
    port: 6379
    password: emei268
    lettuce:
      pool:
        max-idle: 8
        max-active: 8
        min-idle: 0
        max-wait: 200ms
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javadb1?characterEncoding=utf-8
    username: root
    password: Lzc8081501.
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.lzc.study.entity
logging:
  level:
    com.lzc.study.mapper: debug

